#!/bin/bash
# ---------- RESOURCES REQUIRED -------------
# Resources are selected using special comments in the script which begin with
#   #SBATCH
# Modify the parameters to the #SBATCH lines below to your needs.

# These lines request one computer with 4 MPI tasks.
# No more than 16 tasks. No more than 1 node.
#SBATCH --nodes=1
#SBATCH --ntasks=8

# Request a *total* memory of 2 GB (across all tasks)
#SBATCH --mem=10GB

# The maximum runtime of our job.
#SBATCH --time=23:59:00

# Give our job a name -- helpful if you submit multiple jobs to the queue.
#SBATCH --job-name=alphas_alpha_deg4

# The queue to submit our job to - run
#   sinfo
# to see available queues.
# Different queues can use different resources. Target
# the queue with the shortest walltime to fit your needs to ensure your job runs
# as soon as possible.
# Make sure runtime selected above is within the time limit of the queue
#SBATCH --partition=medium

# Output file
#SBATCH --output=output.txt
# If you want to have an output file for every run, use %j to represent the job (uncomment this line and adjust)
#  #SBATCH --output=output_%j.txt

# Account to use for this module. It should give you priority in the queue. 
#SBATCH --account=aero_acfd

# ----------- COMMANDS TO RUN ----------------
# Load any environment modules you need (uncomment this line and adjust)
module load nektar++/5.8.0 hdf5

# Variable holding the name of our executable
INS=IncNavierStokesSolver

# Run our solver with an input file located in the directory from where you
# submit the job.
mpiexec $INS meshAG16.xml session3d.xml > output.txt 2> log.txt

# Submit this file by running
#   sbatch slurm.job
# Monitor the job queue by running
#   squeue
# If for some reason you need to cancel your job, run
#   scancel <jobid>
# where <jobid> is found by running squeue.
